[project]
name = "amrita-icpc-backend"
version = "0.1.0"
description = "ICPC Coding Platform - Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.1",
    "fastapi>=0.136.3",
    "pydantic[email]>=2.12.5",
    "pydantic-settings>=2.12.0",
    "python-jose[cryptography]>=3.5.0",
    "redis>=7.1.0",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
    "fastapi-keycloak-middleware>=1.6.0",
    "python-keycloak>=7.0.2",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "asyncpg>=0.31.0",
    "greenlet>=3.3.0",
    "minio>=7.2.20",
    "httpx>=0.28.1",
    "python-multipart>=0.0.26",
    "apscheduler>=3.11.2",
    "psycopg2-binary>=2.9.12",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pyrefly>=1.0.0",
    "ruff>=0.14.12",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
extend-safe-fixes = ["F841"]
select = ["E", "F", "I", "N", "W"]
ignore = ["E501", "N805", "N818"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
files = ["app"]


[[tool.mypy.overrides]]
module = "fastapi_keycloak_middleware"
ignore_missing_imports = true

[tool.pyrefly]
project-includes = ["app"]
python-version = "3.13.0"
preset = "legacy"
ignore-missing-imports = ["fastapi_keycloak_middleware"]

[[tool.mypy.overrides]]
module = "app.core.clients.database"
ignore_errors = true
