"""add user_audience composite index

Revision ID: 552e5ed1b121
Revises: d5b162c13f80
Create Date: 2026-09-04 21:51:46.800426

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "552e5ed1b121"
down_revision: Union[str, Sequence[str], None] = "d5b162c13f80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_audience_audience_id_user_id",
        "user_audience",
        ["audience_id", "user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_audience_audience_id_user_id", table_name="user_audience")
    # ### end Alembic commands ###
