"""add contest_team_member user contest status index

Revision ID: 82251db306e2
Revises: 98a3c1ff069f
Create Date: 2026-09-04 23:40:44.985403

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82251db306e2"
down_revision: Union[str, Sequence[str], None] = "98a3c1ff069f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_contest_team_member_user_id_contest_id_status",
        "contest_team_member",
        ["user_id", "contest_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_contest_team_member_user_id_contest_id_status",
        table_name="contest_team_member",
    )
    # ### end Alembic commands ###
