"""drop redundant contest_team team_status index

Revision ID: 98a3c1ff069f
Revises: fc4afbd77e27
Create Date: 2026-09-04 23:02:35.620620

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98a3c1ff069f"
down_revision: Union[str, Sequence[str], None] = "fc4afbd77e27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_contest_team_contest_id_team_status"), table_name="contest_team"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_contest_team_contest_id_team_status"),
        "contest_team",
        ["contest_id", "team_status"],
        unique=False,
    )
    # ### end Alembic commands ###
