"""Update BankPermission enum to READ/EDIT/OWNER

Revision ID: e06c41bf54d4
Revises: e81d39256b8c
Create Date: 2026-01-29 15:12:00.462217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06c41bf54d4'
down_revision: Union[str, Sequence[str], None] = 'e81d39256b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE bankpermission RENAME TO bankpermission_old")
    op.execute("CREATE TYPE bankpermission AS ENUM('read', 'edit', 'owner')")
    op.execute((
        "ALTER TABLE bank_share ALTER COLUMN permission TYPE bankpermission USING ("
        "CASE "
        "WHEN permission::text = 'view' THEN 'read'::bankpermission "
        "WHEN permission::text = 'full' THEN 'owner'::bankpermission "
        "ELSE 'read'::bankpermission "  # Default fallback, covers 'edit' implicitly if needed or others
        "END)"
    ))
    op.execute("DROP TYPE bankpermission_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE bankpermission RENAME TO bankpermission_old")
    op.execute("CREATE TYPE bankpermission AS ENUM('view', 'edit', 'full')")
    op.execute((
        "ALTER TABLE bank_share ALTER COLUMN permission TYPE bankpermission USING ("
        "CASE "
        "WHEN permission::text = 'read' THEN 'view'::bankpermission "
        "WHEN permission::text = 'owner' THEN 'full'::bankpermission "
        "ELSE 'view'::bankpermission "
        "END)"
    ))
    op.execute("DROP TYPE bankpermission_old")
    # ### end Alembic commands ###
