"""Add Bank models and sharing

Revision ID: e81d39256b8c
Revises: 
Create Date: 2026-01-29 15:08:29.163448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81d39256b8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_share',
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'EDIT', 'FULL', name='bankpermission'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_id', 'user_id')
    )
    op.add_column('bank', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('bank', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bank', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'bank', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank', type_='foreignkey')
    op.drop_column('bank', 'updated_at')
    op.drop_column('bank', 'created_at')
    op.drop_column('bank', 'created_by')
    op.drop_table('bank_share')
    # ### end Alembic commands ###
