"""add contest_team status indexes

Revision ID: fc4afbd77e27
Revises: 552e5ed1b121
Create Date: 2026-09-04 21:59:13.345071

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc4afbd77e27"
down_revision: Union[str, Sequence[str], None] = "552e5ed1b121"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_contest_team_contest_id_approval_status",
        "contest_team",
        ["contest_id", "approval_status"],
        unique=False,
    )
    op.create_index(
        "ix_contest_team_contest_id_team_status",
        "contest_team",
        ["contest_id", "team_status"],
        unique=False,
    )
    op.create_index(
        "ix_contest_team_contest_id_team_status_approval_status",
        "contest_team",
        ["contest_id", "team_status", "approval_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_contest_team_contest_id_team_status_approval_status",
        table_name="contest_team",
    )
    op.drop_index("ix_contest_team_contest_id_team_status", table_name="contest_team")
    op.drop_index(
        "ix_contest_team_contest_id_approval_status", table_name="contest_team"
    )
    # ### end Alembic commands ###
