"""
One-off: create a single published, registration-open, INDIVIDUAL-mode
contest to drive the load test.

INDIVIDUAL contest_mode auto-confirms a student's solo team the moment it's
created (team_status=CONFIRMED, approval_status=APPROVED - see
ContestTeamService.create_contest_team), unlike TEAM-mode contests where a
newly created team sits in DRAFT until someone separately confirms it. That
makes INDIVIDUAL mode the right fit for a students-only, no-team-flows load
test: register once, start immediately.

Talks to the DB directly (same pattern as scripts/seed_contests.py) rather
than going through the HTTP API, since it just needs to insert one row and
doesn't need an authenticated session to do it.

Usage:
    .venv/bin/python loadtest/setup/setup_contest.py [--days 7]

Prints progress to stdout; the final line is the bare contest UUID so
calling shell scripts can capture it with `tail -1`.
"""

import argparse
import asyncio
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Repo root is two levels up from loadtest/setup/ - needed for `app.*` imports.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from sqlalchemy import select

from app.core.clients.database import SessionLocal
from app.models.contest import Contest
from app.models.user import User
from app.utils.enums import ContestMode, ContestStatus, TeamApprovalMode, UserRole


async def get_or_create_instructor(session) -> User:
    result = await session.execute(
        select(User).where(User.role == UserRole.instructor).limit(1)
    )
    instructor = result.scalars().first()
    if instructor:
        return instructor

    instructor = User(
        id=uuid.uuid4(),
        user_id="loadtest_instructor",
        name="Load Test Instructor",
        email="loadtest_instructor@example.com",
        phone_no="+10000000000",
        role=UserRole.instructor,
        created_at=datetime.now(timezone.utc),
        last_updated=datetime.now(timezone.utc),
    )
    session.add(instructor)
    await session.flush()
    return instructor


async def main(days: int) -> None:
    async with SessionLocal() as session:
        instructor = await get_or_create_instructor(session)

        now = datetime.now(timezone.utc)
        contest = Contest(
            id=uuid.uuid4(),
            name=f"Load Test Contest [{now:%Y-%m-%d %H:%M UTC}]",
            description="Generated by loadtest/setup_contest.py for load testing.",
            image=None,
            is_public=True,
            max_teams=None,  # unlimited - solo teams for every student
            min_team_size=1,
            max_team_size=1,
            rules="Standard programming contest rules apply",
            registration_start=now - timedelta(days=1),
            registration_end=now + timedelta(days=days),
            team_approval_mode=TeamApprovalMode.AUTO_APPROVE,
            contest_mode=ContestMode.INDIVIDUAL,
            status=ContestStatus.PUBLISHED,
            published_at=now,
            published_by=instructor.id,
            created_by=instructor.id,
            created_at=now,
            updated_at=now,
            start_time=now - timedelta(hours=1),  # already live
            end_time=now + timedelta(days=days),
            duration=None,
            show_leaderboard_during_contest=True,
            evaluate_on_submit=True,
            participation_type="INDIVIDUAL_WORKSPACE",
            max_submission_per_question=5,
            shuffle_questions=False,
        )
        session.add(contest)
        await session.commit()

        print(f"Created contest '{contest.name}'")
        print(contest.id)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--days",
        type=int,
        default=7,
        help="How many days the contest should stay open (default 7)",
    )
    args = parser.parse_args()
    asyncio.run(main(args.days))
