#!/usr/bin/env bash
# Open/close SSH tunnels to the live server's Traefik entrypoints for local
# load-test runs. This still hits Traefik on the remote host; it only avoids
# flaky direct TCP routing from this laptop to 10.10.10.23:<port>.

set -euo pipefail

SSH_HOST="${SSH_HOST:-icpc}"
BACKEND_LOCAL_PORT="${BACKEND_LOCAL_PORT:-19000}"
KEYCLOAK_LOCAL_PORT="${KEYCLOAK_LOCAL_PORT:-19080}"
BACKEND_REMOTE_PORT="${BACKEND_REMOTE_PORT:-8000}"
KEYCLOAK_REMOTE_PORT="${KEYCLOAK_REMOTE_PORT:-8080}"
PID_DIR="${TMPDIR:-/tmp}/amrita-icpc-loadtest-tunnels"
ACTION="${1:-start}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
TUNNEL_ENV_FILE="$SCRIPT_DIR/.tunnel.env"
BACKEND_URL="http://127.0.0.1:$BACKEND_LOCAL_PORT"
KEYCLOAK_URL="http://127.0.0.1:$KEYCLOAK_LOCAL_PORT/"

is_sourced() {
    [[ "${BASH_SOURCE[0]}" != "$0" ]]
}

die() {
    echo "$*" >&2
    return 1 2>/dev/null || exit 1
}

emit_exports() {
    cat <<EOF
export HOST=$BACKEND_URL
export KEYCLOAK_SERVER_URL=$KEYCLOAK_URL
EOF
}

apply_exports() {
    export HOST="$BACKEND_URL"
    export KEYCLOAK_SERVER_URL="$KEYCLOAK_URL"
}

write_env_file() {
    cat > "$TUNNEL_ENV_FILE" <<EOF
# Generated by ./loadtest/open_tunnels.sh start.
# run_env_switch_test.sh auto-loads this file when present.
HOST=$BACKEND_URL
KEYCLOAK_SERVER_URL=$KEYCLOAK_URL
EOF
}

show_env_file() {
    if [[ -f "$TUNNEL_ENV_FILE" ]]; then
        echo "Tunnel env file: $TUNNEL_ENV_FILE"
        cat "$TUNNEL_ENV_FILE"
    else
        echo "Tunnel env file: missing ($TUNNEL_ENV_FILE)"
    fi
}

mkdir -p "$PID_DIR"

pid_file() {
    printf '%s/%s.pid\n' "$PID_DIR" "$1"
}

is_running() {
    local pid_file_path="$1"
    [[ -s "$pid_file_path" ]] && kill -0 "$(cat "$pid_file_path")" 2>/dev/null
}

matching_tunnel_pids() {
    local local_port="$1"
    local remote_port="$2"
    pgrep -f "ssh .* -L $local_port:127.0.0.1:$remote_port .*${SSH_HOST}" 2>/dev/null || true
}

port_is_listening() {
    local local_port="$1"
    if command -v lsof >/dev/null 2>&1; then
        lsof -nP -iTCP:"$local_port" -sTCP:LISTEN >/dev/null 2>&1
    else
        return 1
    fi
}

start_tunnel() {
    local name="$1"
    local local_port="$2"
    local remote_port="$3"
    local pid_file_path existing_pid
    pid_file_path="$(pid_file "$name")"

    if is_running "$pid_file_path"; then
        echo "$name tunnel already running (pid $(cat "$pid_file_path")): http://127.0.0.1:$local_port"
        return
    fi

    # A previous shell may have started the same tunnel but lost our pid file.
    # Re-discover and reuse it instead of failing with \"Address already in use\".
    existing_pid="$(matching_tunnel_pids "$local_port" "$remote_port" | tail -1)"
    if [[ -n "$existing_pid" ]] && kill -0 "$existing_pid" 2>/dev/null; then
        echo "$existing_pid" > "$pid_file_path"
        echo "$name tunnel already running (rediscovered pid $existing_pid): http://127.0.0.1:$local_port"
        return
    fi

    if port_is_listening "$local_port"; then
        echo "$name tunnel cannot start: local port $local_port is already in use by another process." >&2
        echo "Run: lsof -nP -iTCP:$local_port -sTCP:LISTEN" >&2
        return 1
    fi

    rm -f "$pid_file_path"
    ssh -f -N \
        -o ExitOnForwardFailure=yes \
        -L "$local_port:127.0.0.1:$remote_port" \
        "$SSH_HOST"

    matching_tunnel_pids "$local_port" "$remote_port" | tail -1 > "$pid_file_path"
    echo "$name tunnel started (pid $(cat "$pid_file_path")): http://127.0.0.1:$local_port -> $SSH_HOST:127.0.0.1:$remote_port"
}

stop_tunnel() {
    local name="$1"
    local local_port="$2"
    local remote_port="$3"
    local pid_file_path pid stopped=0
    pid_file_path="$(pid_file "$name")"

    if is_running "$pid_file_path"; then
        pid="$(cat "$pid_file_path")"
        kill "$pid"
        echo "$name tunnel stopped (pid $pid)"
        stopped=1
    fi

    while read -r pid; do
        [[ -z "$pid" ]] && continue
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid"
            echo "$name tunnel stopped (rediscovered pid $pid)"
            stopped=1
        fi
    done < <(matching_tunnel_pids "$local_port" "$remote_port")

    if [[ "$stopped" -eq 0 ]]; then
        echo "$name tunnel not running"
    fi
    rm -f "$pid_file_path"
}

status_tunnel() {
    local name="$1"
    local local_port="$2"
    local remote_port="$3"
    local pid_file_path existing_pid
    pid_file_path="$(pid_file "$name")"

    if is_running "$pid_file_path"; then
        echo "$name: running (pid $(cat "$pid_file_path")) http://127.0.0.1:$local_port"
        return
    fi

    existing_pid="$(matching_tunnel_pids "$local_port" "$remote_port" | tail -1)"
    if [[ -n "$existing_pid" ]] && kill -0 "$existing_pid" 2>/dev/null; then
        echo "$existing_pid" > "$pid_file_path"
        echo "$name: running (rediscovered pid $existing_pid) http://127.0.0.1:$local_port"
    else
        echo "$name: stopped"
    fi
}

case "$ACTION" in
    start)
        start_tunnel backend "$BACKEND_LOCAL_PORT" "$BACKEND_REMOTE_PORT"
        start_tunnel keycloak "$KEYCLOAK_LOCAL_PORT" "$KEYCLOAK_REMOTE_PORT"
        write_env_file
        if is_sourced; then
            apply_exports
        fi
        cat <<EOF

Wrote tunnel env file:
  $TUNNEL_ENV_FILE

run_env_switch_test.sh auto-loads it, so the normal command is now:
  ./loadtest/run_env_switch_test.sh --scenario loadtest/scenarios/full_user_journey_locustfile.py --shape baseline --students 50

Values:
  HOST=$BACKEND_URL
  KEYCLOAK_SERVER_URL=$KEYCLOAK_URL
EOF
        ;;
    env)
        if is_sourced; then
            apply_exports
            echo "Exported HOST=$HOST"
            echo "Exported KEYCLOAK_SERVER_URL=$KEYCLOAK_SERVER_URL"
        else
            emit_exports
        fi
        ;;
    stop)
        stop_tunnel backend "$BACKEND_LOCAL_PORT" "$BACKEND_REMOTE_PORT"
        stop_tunnel keycloak "$KEYCLOAK_LOCAL_PORT" "$KEYCLOAK_REMOTE_PORT"
        rm -f "$TUNNEL_ENV_FILE"
        echo "Removed tunnel env file: $TUNNEL_ENV_FILE"
        ;;
    restart)
        "$SCRIPT_PATH" stop
        "$SCRIPT_PATH" start
        ;;
    status)
        status_tunnel backend "$BACKEND_LOCAL_PORT" "$BACKEND_REMOTE_PORT"
        status_tunnel keycloak "$KEYCLOAK_LOCAL_PORT" "$KEYCLOAK_REMOTE_PORT"
        echo
        show_env_file
        ;;
    *)
        die "Usage: $SCRIPT_PATH [start|stop|restart|status|env]"
        ;;
esac
